### ISSUE TITLE
Error: This project file is out of date.  Update your .fbp before using --generate

### ISSUE THREAD

**Issue by gstax** [agalasso/phdlogview#16]
Hi,

I am trying to build from source on a linux Debian bookworm box.

I followed https://github.com/agalasso/phdlogview/wiki.

At the last step, I get:

<code>
cmake --build .
[ 14%] Generating LogViewFrameBase.cpp, LogViewFrameBase.h

18:06:52: Error: This project file is out of date.  Update your .fbp before using --generate

18:06:52: Error: Unable to load project: /home/me/sources/phdlogview/phdlogview.fbp

gmake[2]: *** [CMakeFiles/phdlogview.dir/build.make:74 : LogViewFrameBase.cpp] Erreur 6

gmake[1]: *** [CMakeFiles/Makefile2:82 : CMakeFiles/phdlogview.dir/all] Erreur 2

gmake: *** [Makefile:136 : all] Erreur 2

</code>

I failed to find anything helpful on the Net.

Any idea to solve the problem?

Thanks!

**Comment by agalasso** [comment]
@gstax could you try:
```
cmake -D HAVE_WXFB=FALSE ..
cmake --build .
```

**Comment by gstax** [comment]
Works like a charm.

Maybe you should update this page https://github.com/agalasso/phdlogview/wiki accordingly.

Thanks a lot, I can now analyze my logs!

Warm regards

**Comment by agalasso** [comment]
updated the wiki
