### ISSUE TITLE
wxformbuilder project file is not compatible with newer versions of wxFormBuilder

### ISSUE THREAD

**Issue by DerPit** [agalasso/phdlogview#4]
I'm trying to compile this, but it stops with
woodstock:build% cmake --build .
[ 14%] Generating LogViewFrameBase.cpp, LogViewFrameBase.h
11:10:33: Error: This project file is out of date.  Update your .fbp before using --generate

This is with wxformbuilder from git

**Comment by agalasso** [comment]
I have been building on a system with wxformbuilder version 3.5.02-0ubuntu1~xenial1
I guess there must have been some incompatible changes between 3.5.02 and the newer wxformbuilder versions.
Could you try installing one of the older wxformbuilder releases? https://github.com/wxFormBuilder/wxFormBuilder/releases

**Comment by DerPit** [comment]
Ah, that explains it.
I meanwhile had a try at loading the existing .fbp file in the new wxformbuilder gui, and it offers to (try to) convert it.  This seemed to succeed, I saved the new version and with that I could build the program :D
So far it is running without issues.  Should have tried this before - but now it's at least documented (including solution).
Thanks for the fast reply (and for the program anyhow ;^>)

**Comment by agalasso** [comment]
I'm going to keep this issue open since it's a real issue that I'd like to address. I'd prefer to have the fbp file compatible with the latest wxformbuilder versions.

**Comment by agalasso** [comment]
fixed by f05dd7f885f59e4ab8f951469f02a30250ff4c39

**Comment by JamesHarrison** [comment]
@agalasso While this was fixed for 3.2.8, 3.9.0 is the latest available on some distros such as Arch. Would you consider instead pre-generating and source-controlling the generated output rather than requiring the generation to be done as part of compilation? I'm trying to build a PKGBUILD and packages for Arch and struggling as a result of this mismatch.

**Comment by agalasso** [comment]
sure, we can add the pre-generated code to the repo, I'll reopen this issue to track it

**Comment by agalasso** [comment]
fixed by 7f0296090acee82ba93b66cd210d953056c1a94d
invoke cmake like this to use the pre-generated files:
```
cmake -DHAVE_WXFB=0
```
